/**
 * @fileoverview Email Service using Resend
 * 
 * This module provides email-sending functionality for authentication flows.
 * It uses Resend, a modern email API that's easy to set up and reliable.
 * 
 * WHY RESEND?
 * - Simple API with excellent TypeScript support
 * - Free tier available for development
 * - Built-in deliverability optimization
 * - No need to manage SMTP servers
 * 
 * EMAIL TYPES:
 * 1. Verification Email - Sent when a user signs up to verify their email
 * 2. Password Reset Email - Sent when a user requests a password reset
 * 
 * @see https://resend.com/docs/introduction
 */

import { Resend } from 'resend'

/**
 * Initialize the Resend client with API key from environment variables.
 * 
 * WHY create the client at module level?
 * - Reuses the same HTTP connection for multiple requests
 * - More efficient than creating a new client for each email
 * - The Resend client is lightweight and safe to share
 * 
 * The API key should be in your .env file:
 * RESEND_API_KEY=re_xxxxxxxxxxxxxxxx
 */
const resend = new Resend(process.env.RESEND_API_KEY)

/**
 * Sends an email verification link to a newly registered user.
 * 
 * WHEN IS THIS SENT?
 * - When a user signs up with email/password
 * - When a user requests to resend verification email
 * 
 * WHAT HAPPENS NEXT?
 * 1. User clicks the link in the email
 * 2. Link contains a token: /verify-email?token=abc123
 * 3. Backend validates the token and marks email as verified
 * 4. User can now sign in
 * 
 * SECURITY NOTES:
 * - Tokens should be cryptographically random (not predictable)
 * - Tokens should expire after a reasonable time (24 hours here)
 * - The token is generated by Better Auth, not this function
 * 
 * @param email - The recipient's email address
 * @param token - The verification token (generated by Better Auth)
 * @throws Will throw an error if the email fails to send
 */
export async function sendVerificationEmail(
  email: string,
  token: string
) {
  // Build the verification URL with the token as a query parameter
  // NEXT_PUBLIC_APP_URL is required to build absolute URLs in emails
  // (emails need full URLs, not relative paths)
  const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL}/verify-email?token=${token}`

  // Send the email using Resend's API
  // The HTML is simple but functional - for production, consider using
  // a template engine or Resend's built-in templates
  await resend.emails.send({
    // The "from" address must be from a verified domain in Resend
    // For development, Resend provides a default domain
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: email,
    subject: 'Verify your email address',
    html: `
      <h1>Welcome to Kanban!</h1>
      <p>Please verify your email address by clicking the link below:</p>
      <a href="${verificationUrl}">Verify Email</a>
      <p>This link will expire in 24 hours.</p>
    `,
  })
}

/**
 * Sends a password reset link to a user who forgot their password.
 * 
 * WHEN IS THIS SENT?
 * - When a user clicks "Forgot password?" on the sign-in page
 * - When a user enters their email on the forgot-password page
 * 
 * WHAT HAPPENS NEXT?
 * 1. User clicks the link in the email
 * 2. Link contains a token: /reset-password?token=abc123
 * 3. User enters a new password
 * 4. Backend validates the token and updates the password
 * 5. User can sign in with the new password
 * 
 * SECURITY NOTES:
 * - Tokens should expire quickly (1 hour here)
 * - The token should be single-use (consumed after password reset)
 * - The token is generated by Better Auth, not this function
 * 
 * @param email - The recipient's email address
 * @param token - The reset token (generated by Better Auth)
 * @throws Will throw an error if the email fails to send
 */
export async function sendPasswordResetEmail(
  email: string,
  token: string
) {
  // Build the reset URL with the token as a query parameter
  const resetUrl = `${process.env.NEXT_PUBLIC_APP_URL}/reset-password?token=${token}`

  // Send the email using Resend's API
  await resend.emails.send({
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: email,
    subject: 'Reset your password',
    html: `
      <h1>Password Reset Request</h1>
      <p>You requested to reset your password. Click the link below to set a new password:</p>
      <a href="${resetUrl}">Reset Password</a>
      <p>This link will expire in 1 hour.</p>
      <p>If you didn't request this, please ignore this email.</p>
    `,
  })
}
