/**
 * @fileoverview Email Service using Resend
 * 
 * This module provides email-sending functionality for authentication flows.
 * It uses Resend, a modern email API that's easy to set up and reliable.
 * 
 * WHY RESEND?
 * - Simple API with excellent TypeScript support
 * - Free tier available for development
 * - Built-in deliverability optimization
 * - No need to manage SMTP servers
 * 
 * EMAIL TYPES:
 * 1. Verification Email - Sent when a user signs up to verify their email
 * 2. Password Reset Email - Sent when a user requests a password reset
 * 
 * @see https://resend.com/docs/introduction
 */

import { Resend } from 'resend'

/**
 * Initialize the Resend client with API key from environment variables.
 * 
 * WHY create the client at module level?
 * - Reuses the same HTTP connection for multiple requests
 * - More efficient than creating a new client for each email
 * - The Resend client is lightweight and safe to share
 * 
 * The API key should be in your .env file:
 * RESEND_API_KEY=re_xxxxxxxxxxxxxxxx
 */
const resend = new Resend(process.env.RESEND_API_KEY)

/**
 * Sends an email verification link to a newly registered user.
 * 
 * WHEN IS THIS SENT?
 * - When a user signs up with email/password
 * - When a user requests to resend verification email
 * 
 * WHAT HAPPENS NEXT?
 * 1. User clicks the link in the email
 * 2. Link contains a token: /verify-email?token=abc123
 * 3. Backend validates the token and marks email as verified
 * 4. User can now sign in
 * 
 * SECURITY NOTES:
 * - Tokens should be cryptographically random (not predictable)
 * - Tokens should expire after a reasonable time (24 hours here)
 * - The token is generated by Better Auth, not this function
 * 
 * @param email - The recipient's email address
 * @param token - The verification token (generated by Better Auth)
 * @throws Will throw an error if the email fails to send
 */
export async function sendVerificationEmail(
  email: string,
  token: string
) {
  // Build the verification URL with the token as a query parameter
  // NEXT_PUBLIC_APP_URL is required to build absolute URLs in emails
  // (emails need full URLs, not relative paths)
  const verificationUrl = `${process.env.NEXT_PUBLIC_APP_URL}/verify-email?token=${token}`

  // Send the email using Resend's API
  // The HTML is simple but functional - for production, consider using
  // a template engine or Resend's built-in templates
  await resend.emails.send({
    // The "from" address must be from a verified domain in Resend
    // For development, Resend provides a default domain
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: email,
    subject: 'Verify your email address',
    html: `
      <h1>Welcome to Kanban!</h1>
      <p>Please verify your email address by clicking the link below:</p>
      <a href="${verificationUrl}">Verify Email</a>
      <p>This link will expire in 24 hours.</p>
    `,
  })
}

/**
 * Sends a password reset link to a user who forgot their password.
 * 
 * WHEN IS THIS SENT?
 * - When a user clicks "Forgot password?" on the sign-in page
 * - When a user enters their email on the forgot-password page
 * 
 * WHAT HAPPENS NEXT?
 * 1. User clicks the link in the email
 * 2. Link contains a token: /reset-password?token=abc123
 * 3. User enters a new password
 * 4. Backend validates the token and updates the password
 * 5. User can sign in with the new password
 * 
 * SECURITY NOTES:
 * - Tokens should expire quickly (1 hour here)
 * - The token should be single-use (consumed after password reset)
 * - The token is generated by Better Auth, not this function
 * 
 * @param email - The recipient's email address
 * @param token - The reset token (generated by Better Auth)
 * @throws Will throw an error if the email fails to send
 */
export async function sendPasswordResetEmail(
  email: string,
  token: string
) {
  const resetUrl = `${process.env.NEXT_PUBLIC_APP_URL}/reset-password?token=${token}`

  await resend.emails.send({
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: email,
    subject: 'Reset your password',
    html: `
      <h1>Password Reset Request</h1>
      <p>You requested to reset your password. Click the link below to set a new password:</p>
      <a href="${resetUrl}">Reset Password</a>
      <p>This link will expire in 1 hour.</p>
      <p>If you didn't request this, please ignore this email.</p>
    `,
  })
}

/**
 * Sends an invitation email to join a board.
 *
 * WHEN IS THIS SENT?
 * - When a board owner invites a user by email
 *
 * WHAT HAPPENS NEXT?
 * 1. User clicks the link in the email
 * 2. Link contains a token: /invite/[token]
 * 3. Backend validates the token and creates a BoardMember record
 * 4. User is redirected to the board
 *
 * @param email - The recipient's email address
 * @param token - The invitation token (generated by crypto.randomBytes)
 * @param boardName - The name of the board they're invited to
 * @throws Will throw an error if the email fails to send
 */
export async function sendInvitationEmail(
  email: string,
  token: string,
  boardName: string
) {
  const inviteUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${token}`

  await resend.emails.send({
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: email,
    subject: `You've been invited to join "${boardName}"`,
    html: `
      <h1>You've been invited to "${boardName}"</h1>
      <p>Click the link below to join the board:</p>
      <a href="${inviteUrl}">Join Board</a>
      <p>This link will expire in 48 hours.</p>
      <p>If you don't have an account yet, you'll be prompted to create one.</p>
    `,
  })
}

/**
 * One named email recipient — the address + display-name clump every
 * payment email takes, spelled once instead of inline at each signature.
 */
export interface EmailRecipient {
  email: string
  name: string
}

/**
 * The payload of a "receipt pending review" email — one type shared by
 * the upload route (which assembles it) and the sender (which renders
 * it), so the two cannot drift apart.
 */
export interface PaymentPendingEmailSubmission {
  reference: string
  price: number
  currency: string
  submitterName: string
  submitterEmail: string
}

/**
 * Notifies one Administrator that a new payment receipt is awaiting
 * review (subscription-billing issue 05, spec §Administrator
 * notification).
 *
 * WHEN IS THIS SENT?
 * - Once per Administrator, per submission that flips AWAITING_UPLOAD →
 *   PENDING (the receipt upload route fires it best-effort)
 *
 * CALLER CONTRACT:
 * The route treats every failure as log-and-continue: this function may
 * throw, and a thrown email must never fail the user's upload.
 *
 * @param admin - The Administrator recipient (email + display name)
 * @param submission - The newly pending payment (reference, snapshotted
 *   amount, and the submitting user) for the email body
 * @throws Will throw an error if the email fails to send
 */
export async function sendPaymentPendingEmail(
  admin: EmailRecipient,
  submission: PaymentPendingEmailSubmission
) {
  await resend.emails.send({
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: admin.email,
    subject: `Receipt pending review — ${submission.reference}`,
    html: `
      <h1>A receipt is waiting for review</h1>
      <p>Hi ${admin.name},</p>
      <p>
        <strong>${submission.submitterName}</strong> (${
          submission.submitterEmail
        }) uploaded a payment receipt and is waiting on a decision.
      </p>
      <ul>
        <li>Payment reference: <strong>${submission.reference}</strong></li>
        <li>Expected amount: <strong>${submission.price} ${
          submission.currency
        }</strong> (snapshotted at submission)</li>
      </ul>
      <p>Review it in the Administration area — the queue promises a decision within 24 hours.</p>
    `,
  })
}

/**
 * The payload shared by the two payment decision emails — assembled by
 * the decide actions (which read it off the submission), rendered here.
 */
export interface PaymentDecisionEmailSubmission {
  reference: string
  price: number
  currency: string
}

/**
 * Escapes a dynamic value before it is interpolated into email HTML.
 *
 * The rejection reason is free text an Administrator typed, so it must
 * never become markup in the subscriber's inbox (links, images, styling).
 */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Tells the subscriber their payment was approved and their team can now
 * be invited (subscription-billing issue 08, spec story 18).
 *
 * WHEN IS THIS SENT?
 * - Once, right after an Administrator approves a submission —
 *   fire-and-forget from the approve action
 *
 * CALLER CONTRACT:
 * The action treats every failure as log-and-continue: this function may
 * throw, and a thrown email must never roll back the approval
 * (spec story 22).
 *
 * @param subscriber - The approving decision's recipient (email + name)
 * @param submission - The approved payment (reference, snapshotted
 *   amount) plus the period end the approval bought
 * @throws Will throw an error if the email fails to send
 */
export async function sendPaymentApprovedEmail(
  subscriber: EmailRecipient,
  submission: PaymentDecisionEmailSubmission & { periodEnd: Date }
) {
  const billingUrl = `${process.env.NEXT_PUBLIC_APP_URL}/billing`
  const periodEnd = submission.periodEnd.toLocaleDateString('en-US', {
    timeZone: 'UTC',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  await resend.emails.send({
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: subscriber.email,
    subject: `Payment approved — ${submission.reference}`,
    html: `
      <h1>Payment approved</h1>
      <p>Hi ${escapeHtml(subscriber.name)},</p>
      <p>
        Your payment <strong>${submission.reference}</strong> (${
          submission.price
        } ${submission.currency}) was approved. Your Pro subscription is
        running — you can now <strong>invite your team</strong>: Members
        join your Boards for free.
      </p>
      <p>Your subscription runs until ${periodEnd}.</p>
      <p><a href="${billingUrl}">View your billing history</a></p>
    `,
  })
}

/**
 * Tells the subscriber their payment was rejected, with the exact reason
 * (subscription-billing issue 08, spec stories 19 + 20 — the same reason
 * billing history renders next to the attempt, plus the way back in).
 *
 * WHEN IS THIS SENT?
 * - Once, right after an Administrator rejects a submission —
 *   fire-and-forget from the reject action
 *
 * CALLER CONTRACT:
 * The action treats every failure as log-and-continue: this function may
 * throw, and a thrown email must never roll back the rejection
 * (spec story 22).
 *
 * @param subscriber - The rejecting decision's recipient (email + name)
 * @param submission - The rejected payment (reference, snapshotted
 *   amount) plus the stored rejection reason
 * @throws Will throw an error if the email fails to send
 */
export async function sendPaymentRejectedEmail(
  subscriber: EmailRecipient,
  submission: PaymentDecisionEmailSubmission & { reason: string }
) {
  const upgradeUrl = `${process.env.NEXT_PUBLIC_APP_URL}/upgrade`
  const billingUrl = `${process.env.NEXT_PUBLIC_APP_URL}/billing`

  await resend.emails.send({
    from: 'Kanban <onboarding@ZekiAhmed.dev>',
    to: subscriber.email,
    subject: `Payment rejected — ${submission.reference}`,
    html: `
      <h1>Payment rejected</h1>
      <p>Hi ${escapeHtml(subscriber.name)},</p>
      <p>
        Your payment <strong>${submission.reference}</strong> (${
          submission.price
        } ${submission.currency}) was rejected. The reason given by the
        Administrator:
      </p>
      <blockquote><p>${escapeHtml(submission.reason)}</p></blockquote>
      <p>
        One rejected attempt does not dead-end your subscription — submit a
        new receipt to start a fresh attempt.
      </p>
      <p>
        <a href="${upgradeUrl}">Submit a new receipt</a><br />
        <a href="${billingUrl}">View your billing history</a>
      </p>
    `,
  })
}
